name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change this to your production branch if different
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # Disable npm cache to avoid issues with cache key not found
          # cache: 'npm'
      
      - name: Install dependencies
        run: npm install
        
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
        
      - name: Run deployment script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          # Enable debug mode for better error reporting
          CI_DEBUG: "true"
          # Optional overrides
          # FIREBASE_PROJECT_ID: trackedfr
          # BUILD_COMMAND: npm run build:prod
        run: |
          chmod +x ./deploy-ci.sh
          ./deploy-ci.sh
          
      # Only try to upload artifact if the file exists
      - name: Check for deployment summary
        id: check_files
        run: |
          if [ -f "deployment-summary.json" ]; then
            echo "summary_exists=true" >> $GITHUB_OUTPUT
          else
            echo "summary_exists=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload deployment summary
        uses: actions/upload-artifact@v4
        if: steps.check_files.outputs.summary_exists == 'true'
        with:
          name: deployment-summary
          path: deployment-summary.json
          retention-days: 30