name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Change this to your production branch if different
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run deployment script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          # Optional overrides
          # FIREBASE_PROJECT_ID: trackedfr
          # BUILD_COMMAND: npm run build:prod
          # CI_DEBUG: true
        run: |
          chmod +x ./deploy-ci.sh
          ./deploy-ci.sh
          
      - name: Upload deployment summary
        uses: actions/upload-artifact@v3
        if: always()  # Upload even if the deployment fails
        with:
          name: deployment-summary
          path: deployment-summary.json
          retention-days: 30